### ISSUE TITLE
exit status 3221225477

### ISSUE THREAD

**Issue by xackery** [inkyblackness/imgui-go-examples#12] opened 2021-03-29 23:46 UTC
OS: Windows 7 latest
go version go1.16 windows/amd64
ran `go get -u github.com/go-gl/glfw/v3.3/glfw` successfully.

inside root path of examples:
<omitted>\imgui-go-examples\cmd\example_glfw_opengl2>go run -tags 'glfw' .
exit status 3221225477

same occurs with opengl3

**Comment by dertseha** [comment] 2021-04-02 17:18
Hello and thank you for your message!
May I ask you to help out a little with your post - what is the expected behaviour, and what exactly is happening?

I can run the example with go1.16 on Win10, the window opens, showing the sample UI. And when I close the application, an exit code of 0 is reported.
By the way, the examples use `glfw/v3.2` - see `internal/platforms/glfw.go`.

**Comment by xackery** [comment] 2021-04-06 19:23
Hi @dertseha 
expected behavior is what you described, the UI showing, and a return code of 0

What I get is an immediate return on start with exit status. I never see the UI.

> go run -tags 'glfw' .
exit status 3221225477

Based on your "by the way" comment, I ran:

> go get -u github.com/go-gl/glfw/v3.2/glfw
go get: upgraded github.com/go-gl/glfw v0.0.0-20191125211704-12ad95a8df72 => v0.0.0-20210311203641-62640a716d48


then ran
> \imgui-go-examples\cmd\example_glfw_opengl2>go run -tags 'glfw' .
exit status 3221225477

and it failed again..
From what I can tell, I never get any progress.

I tried adding this to the example:

func main() {
	fmt.Println("starting")

and it still simply states:

imgui-go-examples\cmd\example_glfw_opengl2>go run -tags 'glfw' .
exit status 3221225477

**Comment by xackery** [comment] 2021-04-06 19:30
After running go get -u github.com/go-gl/glfw/v3.2/glfw
my go.mod changed to (attached):
<img width="1201" alt="Screen Shot 2021-04-06 at 12 29 30 PM" src="https://user-images.githubusercontent.com/845670/113767740-e8077200-96d3-11eb-9da8-c29d6f64e786.png">

**Comment by dertseha** [comment] 2021-04-07 15:22
Thank you for the details.
If the process doesn't even properly come up, then I don't think I can help you, especially if I can't even reproduce it. The wrapper doesn't have an `init` function that might do something weird.

Perhaps you can retrieve more details if it's possible to start and step into the process with a debugger. (I don't know whether delve supports this).

If it helps, exit status 3221225477 resolves to 0xC0000005 (hexadecimal), which is the typical "access violation" error of MS Windows.

Tagging with `help wanted` as I don't know how any other way on how to proceed on this.

**Comment by Vinschni** [comment] 2021-04-08 12:12
Hi @xackery, 
you could add a defered panic recovery function as explained [here](https://www.digitalocean.com/community/tutorials/handling-panics-in-go).

For example add:
```golang
 defer func() {
        if err := recover(); err != nil {
            log.Println("panic occurred:", err)
        }
    }()
```
as first statement in your man function and place a breakpoint there. Then you can inspect the program status before exit.

**Comment by xackery** [comment] 2021-04-08 22:26
> ```go
>  defer func() {
>         if err := recover(); err != nil {
>             log.Println("panic occurred:", err)
>         }
>     }()
> ```

Adding this code and running it causes the same exit status 3221225477 when doing go build -tags 'glfw' .

Doing go build -tags 'glfw' . will succeed to build the exe, but running the exe example_glfw_opengl2.exe will show nothing. Starts then immediately exits.


From what I can deduce, this error is occuring prior to the func main() is even ran

**Comment by xackery** [comment] 2021-04-08 22:55
also with above code included:
```
imgui-go-examples\cmd\example_glfw_opengl2>dlv debug . --build-flags "-tags 'glfw'"
Type 'help' for list of commands.
(dlv) c
Process 23596 has exited with status 3221225477
```

**Comment by xackery** [comment] 2021-04-08 22:57
i upgraded and flushed my env , starting from scratch, moving to latest 1.16.3
above dlv reporting still happens. A bit perplexed.

**Comment by Vinschni** [comment] 2021-04-09 15:36
Where did you add the panic recover code?

**Comment by xackery** [comment] 2021-04-10 00:32
@Vinschni 
```go
// +build glfw

package main

import (
	"fmt"
	"log"
	"os"

	"github.com/inkyblackness/imgui-go/v4"

	"github.com/inkyblackness/imgui-go-examples/internal/example"
	"github.com/inkyblackness/imgui-go-examples/internal/platforms"
	"github.com/inkyblackness/imgui-go-examples/internal/renderers"
)

func main() {
	defer func() {
		if err := recover(); err != nil {
			log.Println("panic occurred:", err)
		}
	}()
	context := imgui.CreateContext(nil)
	defer context.Destroy()
	io := imgui.CurrentIO()

	platform, err := platforms.NewGLFW(io, platforms.GLFWClientAPIOpenGL2)
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(-1)
	}
	defer platform.Dispose()

	renderer, err := renderers.NewOpenGL2(io)
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(-1)
	}
	defer renderer.Dispose()

	example.Run(platform, renderer)
}

```

**Comment by dertseha** [comment] 2021-04-10 06:02
At this point I doubt it has anything to do with the Go code. If the Go runtime doesn't event fully come up, and the OS itself reports the typical (and generic) exit code for an access violation, it has to originate from the native (non-Go) world.
I was hoping a debugger would be able to step into the whole process-initialization phase and catch such an issue early on, apparently Delve cannot.

This can be caused by any number of sources - GCC toolchain putting together something weird, the used libraries - and even the available drivers.

Another idea could be to make cross-checks to see if this is caused by a particular component:
* Create a dedicated sample application only dependent on `go-gl/gl` and have main() call just `gl.Init()`
  * side note: try it out with different variants of gl -- `v2.1/gl` and `v3.2-core/gl`
* Create a dedicated sample application only dependent on `glfw` and have main() call just `glfw.Init()` and `glfw.Terminate()`
  * side note: try it out with different variants: `v3.2/glfw` and `v3.3/glfw`
* Create a dedicated sample application only dependent on `imgui-go` and have main() call just `imgui.CreateContext(nil)` and `context.Destroy()`

In each case, run it and see in which case the error appears. This would help pinpoint with which library it happens, as these applications take only the specific library to initialize it.

If none of these cases have an issue, then try combinations: sample applications having both `glfw` and `go-gl/gl` and so on -- You could also achieve this by using existing examples like this one: https://github.com/go-gl/example/tree/master/gl21-cube

**Comment by xackery** [comment] 2021-04-21 07:53
I dived deeper and found that it had to do with my gcc compiler linking/setup.. i'll post more details later

**Comment by dertseha** [comment] 2021-09-26 15:29
In case you find the time to update what the original issue with the compiler and linker setup was, feel free to summarize here.

Apart from that, closing this issue now.

**Closed as completed by dertseha** 2021-09-26 15:29 UTC
